#!/usr/bin/python3

import os
import re
import sys
import datetime



def main(connect, dump):

	current_path = os.getcwd()
	config_file = get_config_file(current_path)

	mysql_connection = get_mysql_connection(config_file)
	conn_str = get_mysql_connection_string(mysql_connection, dump)

	if connect:
		os.system(conn_str)

	else:
		print(conn_str)

	return True



def get_config_file(initial_path, filename='wp-config.php'):

	while not os.path.isfile( os.path.join(initial_path, filename) ):
		initial_path = initial_path.rsplit('/', 1)[0]
		if initial_path=='':
			return None

	return os.path.join(initial_path, filename)



def get_mysql_connection(config_file):

	mysql_connection = {}
	reg = re.compile(r'.*define.*\(\w*[\'"](.*?)[\'"], *[\'"](.*?)[\'"]\w*\).*')

	with open(config_file, 'r') as infile:
		for line in infile:
			if 'DB_' in line:
				pair = reg.search(line)
				if 'groups' in dir(pair):
					key = pair.groups()[0]
					value = pair.groups()[1]
					mysql_connection[key] = value

	return mysql_connection



def get_mysql_connection_string(conn, dump):

	#skipopt = ''
	skipopt = ' --skip-opt' # Force rows to separate INSERT statements, great for versioning.

	if not 'DB_USER' in conn.keys() or not 'DB_PASSWORD' in conn.keys():
		return None

	ifdump = ''
	if dump:
		ifdump='dump'

	conn_str = 'mysql%s -u"%s" -p"%s"' % (ifdump, conn['DB_USER'], conn['DB_PASSWORD'], )

	if 'DB_HOST' in conn.keys():
		conn_str += ' -h"%s"' % (conn['DB_HOST'], )

	if 'DB_NAME' in conn.keys():
		conn_str += ' %s' % (conn['DB_NAME'], )
		db_name = conn['DB_NAME']
	else:
		db_name = 'wordpress'

	if dump:
		timestring = str(datetime.datetime.now().strftime('%Y-%m-%d_%H%M'))
		conn_str += '%s > %s_%s.sql' % (skipopt, db_name, timestring,)

	return conn_str



if __name__=='__main__':

	connect = False
	dump = False

	if 1 < len(sys.argv) and sys.argv[1] in ['c', 'C', '-c', '-C']:
		connect = True

	if 1 < len(sys.argv) and sys.argv[1] in ['d', 'D', '-d', '-D']:
		dump = True

	main(connect, dump)

